version: '3.5'

services:
  sf-eduardoaf-web:
    container_name: sf-eduardoaf-web
    build:
      # apunta al Dockerfile
      context: ./docker/nginx
      args:
        UID: $U_ID
    ports:
      - 400:80
    volumes:
      - ./public:/appdata/www/public
    depends_on:
      - sf-eduardoaf-be
    networks:
      - sf-eduardoaf-net

  sf-eduardoaf-be:
    container_name: sf-eduardoaf-be
    build:
      context: docker/php
      args:
        UID: $U_ID
    environment:
      # variables necesarias para xdebug
      PHP_IDE_CONFIG: serverName=Dockereduardoaf
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9005
    volumes:
      # nocopy evita hacer la copia del contenedor al host (nuestra maquina)
      - sf-eduardoaf-be-sync:/appdata/www:nocopy
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa

    networks:
      - sf-eduardoaf-net
      - mariadb-univ_net
volumes:
  sf-eduardoaf-be-sync:
    external: true

networks:
  sf-eduardoaf-net:
  mariadb-univ_net:
    external: true


